### ISSUE TITLE
BEAR.Sunday 1.0 todo list 

### ISSUE THREAD

**Issue by koriym** [koriym/BEAR.Sunday#52]
- [x] Hal
- [x] Read / Write separate store with @QueryRepository
- [x] Reverse route
- [x] Etag output
- [x] 304 Not modified
- [x] stdin for PUT / PATCH ..
- [x] Clear aop class files in dev
- [x] Master / Slave DB
- [x] HTML
- [x] BEAR.Skeleton 
- [x] Documentation

**Comment by koriym** [comment]
**304 Not modified** checked

**Comment by koriym** [comment]
**stdin for PUT / PATCH** checked

**Comment by koriym** [comment]
**BEAR.Skeleton** checked

**Comment by koriym** [comment]
**Clear aop class** checked.

**Comment by koriym** [comment]
all done.
